# Generated by Django 3.2.9 on 2021-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20211209_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
