# Generated by Django 3.2.9 on 2021-12-09 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_alter_tweet_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='uid',
        ),
        migrations.AddField(
            model_name='tweet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
