# Generated by Django 4.0 on 2021-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_auto_20211211_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
