# Generated by Django 4.0 on 2021-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_alter_tweet_options_tweet_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_testing_record',
            field=models.BooleanField(default=False),
        ),
    ]
