# Generated by Django 4.0 on 2021-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_tweet_is_testing_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
